import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetTime;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

import javax.swing.JComboBox;

import javafx.scene.control.ComboBox;  
    
public class Time   
{      
	static DateTimeFormatter FOMATTER = DateTimeFormatter.ofPattern("hh a  ");
	static DateTimeFormatter FOMATTER2 = DateTimeFormatter.ofPattern("mm a  ");
	//Local time instance
	static OffsetTime pickupTime1 = OffsetTime.now().plusMinutes(30);
	static OffsetTime pickupTime2 = OffsetTime.now().plusMinutes(45);
	static OffsetTime pickupTime3 = OffsetTime.now().plusMinutes(60);
	static OffsetTime pickupTime4 = OffsetTime.now().plusMinutes(75);
	static OffsetTime pickupTime5 = OffsetTime.now().plusMinutes(90);
	static OffsetTime pickupTime6 = OffsetTime.now().plusMinutes(105);
	static OffsetTime pickupTime7 = OffsetTime.now().plusMinutes(120);
	static OffsetTime pickupTime8 = OffsetTime.now().plusMinutes(135);
	static OffsetTime pickupTime9 = OffsetTime.now().plusMinutes(150);
	static OffsetTime pickupTime10 = OffsetTime.now().plusMinutes(165);
	static OffsetTime pickupTime11 = OffsetTime.now().plusMinutes(180);
	static OffsetTime pickupTime12 = OffsetTime.now().plusMinutes(195);
	static OffsetTime pickupTime13 = OffsetTime.now().plusMinutes(210);
	static OffsetTime pickupTime14 = OffsetTime.now().plusMinutes(225);
	static OffsetTime pickupTime15 = OffsetTime.now().plusMinutes(240);
	static OffsetTime pickupTime16 = OffsetTime.now().plusMinutes(255);
	static OffsetTime pickupTime17 = OffsetTime.now().plusMinutes(270);
	static OffsetTime pickupTime18 = OffsetTime.now().plusMinutes(285);
	static OffsetTime pickupTime19 = OffsetTime.now().plusMinutes(290);
	static OffsetTime pickupTime20 = OffsetTime.now().plusMinutes(305);
	static OffsetTime pickupTime21 = OffsetTime.now().plusMinutes(320);
	static OffsetTime pickupTime22 = OffsetTime.now().plusMinutes(335);
	static OffsetTime pickupTime23 = OffsetTime.now().plusMinutes(350);
	static OffsetTime pickupTime24 = OffsetTime.now().plusMinutes(365);
	static OffsetTime pickupTime25 = OffsetTime.now().plusMinutes(380);
	static OffsetTime pickupTime26 = OffsetTime.now().plusMinutes(395);
	static OffsetTime pickupTime27 = OffsetTime.now().plusMinutes(410);
	static OffsetTime pickupTime28 = OffsetTime.now().plusMinutes(425);
	static OffsetTime pickupTime29  = OffsetTime.now().plusMinutes(440);
	static OffsetTime pickupTime30 = OffsetTime.now().plusMinutes(445);
	static OffsetTime pickupTime31 = OffsetTime.now().plusMinutes(460);
	static OffsetTime pickupTime32 = OffsetTime.now().plusMinutes(475);
	static OffsetTime pickupTime33 = OffsetTime.now().plusMinutes(490);
	static OffsetTime pickupTime34 = OffsetTime.now().plusMinutes(505);
	static OffsetTime pickupTime35 = OffsetTime.now().plusMinutes(520);
	static OffsetTime pickupTime36 = OffsetTime.now().plusMinutes(535);
	static OffsetTime pickupTime37 = OffsetTime.now().plusMinutes(550);
	static OffsetTime pickupTime38 = OffsetTime.now().plusMinutes(565);
	static OffsetTime pickupTime39 = OffsetTime.now().plusMinutes(580);
	static OffsetTime pickupTime40 = OffsetTime.now().plusMinutes(595);
	static OffsetTime pickupTime41 = OffsetTime.now().plusMinutes(610);
	static OffsetTime pickupTime42 = OffsetTime.now().plusMinutes(625);
	static OffsetTime pickupTime43 = OffsetTime.now().plusMinutes(640);
	static OffsetTime pickupTime44 = OffsetTime.now().plusMinutes(655); 
	static OffsetTime pickupTime45 = OffsetTime.now().plusMinutes(670); 
	static String localTimeString1 = FOMATTER.format(pickupTime1);
	static String localTimeString2 = FOMATTER.format(pickupTime2);
	static String localTimeString3 = FOMATTER.format(pickupTime3);
	static String localTimeString4 = FOMATTER.format(pickupTime4);
	static String localTimeString5 = FOMATTER.format(pickupTime5);
	static String localTimeString6 = FOMATTER.format(pickupTime6);
	static String localTimeString7 = FOMATTER.format(pickupTime7);
	static String localTimeString8 = FOMATTER.format(pickupTime8);
	static String localTimeString9 = FOMATTER.format(pickupTime9);
	static String localTimeString10 = FOMATTER.format(pickupTime10);
	static String localTimeString11 = FOMATTER.format(pickupTime11);
	static String localTimeString12 = FOMATTER.format(pickupTime12);
	static String localTimeString13 = FOMATTER.format(pickupTime13);
	static String localTimeString14 = FOMATTER.format(pickupTime14);
	static String localTimeString15 = FOMATTER.format(pickupTime15);
	static String localTimeString16 = FOMATTER.format(pickupTime16);
	static String localTimeString17 = FOMATTER.format(pickupTime17);
	static String localTimeString18 = FOMATTER.format(pickupTime18);
	static String localTimeString19 = FOMATTER.format(pickupTime19);
	static String localTimeString20 = FOMATTER.format(pickupTime20);
	static String localTimeString21 = FOMATTER.format(pickupTime21);
	static String localTimeString22 = FOMATTER.format(pickupTime22);
	static String localTimeString23 = FOMATTER.format(pickupTime23);
	static String localTimeString24 = FOMATTER.format(pickupTime24);
	static String localTimeString25 = FOMATTER.format(pickupTime25);
	static String localTimeString26 = FOMATTER.format(pickupTime26);
	static String localTimeString27 = FOMATTER.format(pickupTime27);
	static String localTimeString28 = FOMATTER.format(pickupTime28);
	static String localTimeString29 = FOMATTER.format(pickupTime29);
	static String localTimeString30 = FOMATTER.format(pickupTime30);
	static String localTimeString31 = FOMATTER.format(pickupTime31);
	static String localTimeString32 = FOMATTER.format(pickupTime32);
	static String localTimeString33 = FOMATTER.format(pickupTime33);
	static String localTimeString34 = FOMATTER.format(pickupTime34);
	static String localTimeString35 = FOMATTER.format(pickupTime35);
	static String localTimeString36 = FOMATTER.format(pickupTime36);
	static String localTimeString37 = FOMATTER.format(pickupTime37);
	static String localTimeString38 = FOMATTER.format(pickupTime38);
	static String localTimeString39 = FOMATTER.format(pickupTime39);
	static String localTimeString40 = FOMATTER.format(pickupTime40);
	static String localTimeString41 = FOMATTER.format(pickupTime41);
	static String localTimeString42 = FOMATTER.format(pickupTime42);
	static String localTimeString43 = FOMATTER.format(pickupTime43);
	static String localTimeString44 = FOMATTER.format(pickupTime44);
	static String localTimeString45 = FOMATTER.format(pickupTime45);
	static String localTimeStringa = FOMATTER2.format(pickupTime1);
	static String localTimeStringb = FOMATTER2.format(pickupTime2);
	static String localTimeStringc = FOMATTER2.format(pickupTime3);
	static String localTimeStringd = FOMATTER2.format(pickupTime4);
	static String localTimeStringe = FOMATTER2.format(pickupTime5);
	static String localTimeStringf = FOMATTER2.format(pickupTime6);
	static String localTimeStringg = FOMATTER2.format(pickupTime7);
	static String localTimeStringh = FOMATTER2.format(pickupTime8);
	static String localTimeStringi = FOMATTER2.format(pickupTime9);
	static String localTimeStringj = FOMATTER2.format(pickupTime10);
	static String localTimeStringk = FOMATTER2.format(pickupTime11);
	static String localTimeStringl = FOMATTER2.format(pickupTime12);
	static String localTimeStringm = FOMATTER2.format(pickupTime13);
	static String localTimeStringn = FOMATTER2.format(pickupTime14);
	static String localTimeStringo = FOMATTER2.format(pickupTime15);
	static String localTimeStringp = FOMATTER2.format(pickupTime16);
	static String localTimeStringq = FOMATTER2.format(pickupTime17);
	static String localTimeStringr = FOMATTER2.format(pickupTime18);
	static String localTimeStrings = FOMATTER2.format(pickupTime19);
	static String localTimeStringt = FOMATTER2.format(pickupTime20);
	static String localTimeStringu = FOMATTER2.format(pickupTime21);
	static String localTimeStringv = FOMATTER2.format(pickupTime22);
	static String localTimeStringw = FOMATTER2.format(pickupTime23);
	static String localTimeStringx = FOMATTER2.format(pickupTime24);
	static String localTimeStringy = FOMATTER2.format(pickupTime25);
	static String localTimeStringz = FOMATTER2.format(pickupTime26);
	static String localTimeStringaa = FOMATTER2.format(pickupTime27);
	static String localTimeStringbb = FOMATTER2.format(pickupTime28);
	static String localTimeStringcc = FOMATTER2.format(pickupTime29);
	static String localTimeStringdd = FOMATTER2.format(pickupTime30);
	static String localTimeStringee = FOMATTER2.format(pickupTime31);
	static String localTimeStringff = FOMATTER2.format(pickupTime32);
	static String localTimeStringgg = FOMATTER2.format(pickupTime33);
	static String localTimeStringhh = FOMATTER2.format(pickupTime34);
	static String localTimeStringii = FOMATTER2.format(pickupTime35);
	static String localTimeStringjj = FOMATTER2.format(pickupTime36);
	static String localTimeStringkk = FOMATTER2.format(pickupTime37);
	static String localTimeStringll = FOMATTER2.format(pickupTime38);
	static String localTimeStringmm = FOMATTER2.format(pickupTime39);
	static String localTimeStringnn = FOMATTER2.format(pickupTime40);
	static String localTimeStringoo = FOMATTER2.format(pickupTime41);
	static String localTimeStringpp = FOMATTER2.format(pickupTime42);
	static String localTimeStringqq = FOMATTER2.format(pickupTime43);
	static String localTimeStringrr = FOMATTER2.format(pickupTime44);
	static String localTimeStringss = FOMATTER2.format(pickupTime45);
	
}